---
title: "assignment"
author: "Leonardo Zingler Herreo, Anna Chamot, Julio Eduardo Cáceres Pajuelo, "
date: "2025-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

What is the topic?

Chromatin accessibility and gene expression in spermatogonial stem cells during maturation and adulthood in a model of early life stress.

What data will you be using?

We will use ATAC-seq and, if possible, RNA-seq datasets generated in our lab (Mansuy lab) from spermatogonial stem cells of mice at postnatal day 15 and in adulthood (between 2.5 and 3.5 months of age), under two conditions: stress and control.

What are the analyses you wish to reproduce, or the questions you wish to answer?

The main question is whether changes in the epigenome induced by early life stress persist into adulthood. These changes will be assessed through chromatin accessibility analysis, and compared with gene expression data from the same tissue to evaluate whether alterations in accessibility can partially explain changes in gene expression. Our experimental design aims to identify lasting changes in chromatin structure, specifically investigating whether spermatogonial stem cells can retain a form of chromatin memory.
